distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-8.7-all.zip
networkTimeout=10000
validateDistributionUrl=false
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
# מאפשר שימוש בספריות AndroidX החדשות
android.useAndroidX=true
# מאפשר המרה אוטומטית של ספריות ישנות לפורמט החדש (חשוב ל-API 19)
android.enableJetifier=true